name: Mago

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  run:
    name: Run Mago
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PHP
        uses: ./.github/actions/setup-php

      - name: Install Mago
        run: composer config --no-plugins allow-plugins.carthage-software/mago true; composer require --dev carthage-software/mago:1.9.1

      - name: Run Mago
        run: ./vendor/bin/mago --config .mago/mago.toml analyze
