name: Psalm

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  run:
    name: Run Psalm
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions:6.14.3
        with:
          security_analysis: true
